### ISSUE TITLE
min:1 fails to validate empty string in non-strict mode

### ISSUE THREAD

**Issue by radmen** [poppinss/indicative#159]
`min:1` rule fails to validate empty strings.
The problem occurs only in `standard` mode. In `strict` mode validation works correctly.

**Comment by RomainLanz** [comment]
This is why all the file are in strict mode and you should always use strict mode.

This is more a JavaScript language thing, I don't know if @thetutlage can/wanna do something about it.

**Comment by radmen** [comment]
@RomainLanz shouldn't this validator be always in strict mode? IMO this should be enough.

**Comment by radmen** [comment]
BTW,

> you should always use strict mode

I've done this in my Adonis project however, this feature is not documented.

**Comment by RomainLanz** [comment]
> shouldn't this validator be always in strict mode? IMO this should be enough.

If you browse indicative files you can see that they all begin with `'use strict'`. We cannot do more.

> I've done this in my Adonis project however, this feature is not documented.

Because there's no need to document this and it's out of the scope of Adonis. Strict mode is a Javascript "feature". Your application may work completely fine without being in strict mode, you just need to learn what changes will occur if you are in one mode or another.

Here's more information about JS Strict mode https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

**Comment by radmen** [comment]
@RomainLanz I'm talking about this little thingy:

https://github.com/poppinss/indicative/blob/9bf99faafb5a553f26489a8d152ac0c2be201407/src/Validations/index.js#L30-L32

It's possible to set Indicative in `strict` mode which validates all non-undefined values.

**Comment by RomainLanz** [comment]
Damnit, I was thinking you were speaking about JS Mode and not Indicative's one 😂 

Forget what I said.

**Comment by thetutlage** [comment]
Shouldn’t that be validated via `required` rule?

**Comment by radmen** [comment]
> Shouldn’t that be validated via required rule?

Not always.

Given this rule:

```js
{
    name: 'min:1'
}
```

I expect that *if* `name` is defined in data object it should be validated with `min:1`.
`required` assumes that `name` has to be defined every time.

**Comment by thetutlage** [comment]
Empty string is not existy value, it works same as Javascript `if`

You must sanitize data to convert empty strings to `null`

**Comment by radmen** [comment]
> Empty string is not existy value, it works same as Javascript if

Yea, I know. That's the problem.

If I pass data like `{name: ''}`, `{ name: 'min:1'}` rule should fail. It should not treat empty string as *not existy* value.

**Comment by thetutlage** [comment]
There are so many other people who want this to behave as undefined for so many other reasons.

Sanitizing data is the only way here

**Comment by radmen** [comment]
> There are so many other people who want this to behave as undefined for so many other reasons.

I'm talking here only about `min` validation. Should it also apply to it? I understand that for other validations this makes sense.

> Sanitizing data is the only way here

I'd say that changing mode to `strict` is the only way :)

**Comment by erzzo** [comment]
I've come to the same thing and agree with @radmen . For now I need to figure out how to set `strict` mode in adonjis.js.

**Comment by radmen** [comment]
@erzzo you can add it to hooks in `start/hooks.js` file:

```js
const Modes = require('indicative/src/Modes')
const { hooks } = require('@adonisjs/ignitor')

hooks.after.providersBooted(() => {
    Modes.set('strict')
})
```

**Comment by thetutlage** [comment]
@radmen @erzzo I have been cleaning Indicative for a while and made it compatible to work in browsers. 

1. It has some breaking changes.
2. You can install it using `npm i indicative@next`
3. Docs are here https://epic-albattani-83fe42.netlify.com/docs/installation

Feel free to share your feedback.

Also instead of modes new version uses `configure` method to define settings. More here https://epic-albattani-83fe42.netlify.com/docs/upgrading-from-3#_modes

**Comment by thetutlage** [comment]
Should be good with the new version

**Comment by radmen** [comment]
@thetutlage I'd argue with that. The new version introduces an easier way to declare strict mode. It does not solve this issue.

**Comment by thetutlage** [comment]
Yeah that's true, since not everyone wants the behavior you want. So you can simply set the mode for yourself

**Comment by radmen** [comment]
Yup, will do so :)
